# Generated by Django 2.2.4 on 2020-05-26 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Order Placed'), (1, 'Order Confirmed'), (2, 'Packing'), (3, 'Shipped'), (4, 'Out for Delivery'), (5, 'Delivered'), (6, 'Order Cancelled'), (7, 'Return Request Placed'), (8, 'Return Request Acknowledged'), (9, 'Courier Service Informed'), (10, 'Return Product Verified'), (11, 'Refund Completed')], default=0)),
                ('order_placed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('packing_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, default=products.models.one_week_hence, null=True)),
                ('order_cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('return_request_placed_date', models.DateTimeField(blank=True, null=True)),
                ('return_request_acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('courier_service_informed_date', models.DateTimeField(blank=True, null=True)),
                ('return_product_verified_date', models.DateTimeField(blank=True, null=True)),
                ('refund_completed_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.IntegerField(choices=[(0, 'Your Order is Placed'), (1, 'Your Order is Confirmed'), (2, 'Order Packed'), (3, 'Your product is Shipped'), (4, 'Your product is out for Delivery'), (5, 'Your product is successfully Delivered'), (6, 'Your order is Cancelled'), (7, 'Your Return Request is Placed'), (8, 'Your Return Request is Acknowledged'), (9, 'Courier Service near you is Informed'), (10, 'Return Product Verified'), (11, 'Refund Completed')], default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
