# Generated by Django 2.2.4 on 2020-05-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200522_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.IntegerField(choices=[('0', 'Order Placed'), ('1', 'Order Confirmed'), ('2', 'Packing'), ('3', 'Shipped'), ('4', 'Out for Delivery'), ('5', 'Delivered'), ('6', 'Order Cancelled'), ('7', 'Return Request Placed'), ('8', 'Return Request Acknowledged'), ('9', 'Courier Service Informed'), ('10', 'Return Product Verified'), ('11', 'Refund Completed')], default='Order Placed', max_length=200),
        ),
    ]
