# Generated by Django 2.2.4 on 2020-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
