# Generated by Django 2.2.4 on 2020-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200421_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
