# Generated by Django 2.2.4 on 2020-05-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200522_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
