# Generated by Django 2.2.4 on 2020-05-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_admin_returned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='ordered_date',
            new_name='order_placed_date',
        ),
    ]
