# Generated by Django 2.2.4 on 2020-04-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200422_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='category/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url_1',
            field=models.ImageField(blank=True, null=True, upload_to='product/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url_2',
            field=models.ImageField(blank=True, null=True, upload_to='product/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url_3',
            field=models.ImageField(blank=True, null=True, upload_to='product/img'),
        ),
    ]
