# Generated by Django 2.2.4 on 2020-05-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200522_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='returned_date',
            new_name='return_request_placed_date',
        ),
        migrations.AddField(
            model_name='admin',
            name='courier_service_informed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='order_cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='order_confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='out_for_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='packing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='refund_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='return_product_verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='return_request_acknowledged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.IntegerField(choices=[(0, 'Order Placed'), (1, 'Order Confirmed'), (2, 'Packing'), (3, 'Shipped'), (4, 'Out for Delivery'), (5, 'Delivered'), (6, 'Order Cancelled'), (7, 'Return Request Placed'), (8, 'Return Request Acknowledged'), (9, 'Courier Service Informed'), (10, 'Return Product Verified'), (11, 'Refund Completed')], default=0),
        ),
    ]
