# Generated by Django 2.2.4 on 2020-05-24 11:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200522_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='delivered_date',
            field=models.DateTimeField(blank=True, default=products.models.one_week_hence, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(null=True),
        ),
    ]
