# Generated by Django 2.2.4 on 2020-05-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
