# Generated by Django 2.2.4 on 2020-04-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200429_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
