# Generated by Django 2.2.4 on 2020-05-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200504_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist_products',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='products.Product'),
        ),
    ]
