# Generated by Django 2.2.4 on 2020-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200429_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
