# Generated by Django 2.2.4 on 2020-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200507_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='default profile pic.png', upload_to='profile/img'),
        ),
    ]
