# Generated by Django 2.2.4 on 2020-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200429_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date1',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
