# Generated by Django 2.2.4 on 2020-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200507_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='/default_profile_pic.png', upload_to='profile/img'),
        ),
    ]
