# Generated by Django 2.2.4 on 2020-05-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200507_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='profile/img/default_profile_pic.png', upload_to='profile/img'),
        ),
    ]
