# Generated by Django 2.2.4 on 2020-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200507_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='profile/img'),
        ),
    ]
