# Generated by Django 2.2.4 on 2020-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200508_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, default='1', max_length=5),
        ),
    ]
