# Generated by Django 2.2.4 on 2020-05-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20200510_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
