# Generated by Django 2.2.4 on 2020-05-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20200510_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
