# Generated by Django 2.2.4 on 2020-05-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
