# Generated by Django 2.2.4 on 2020-05-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
