# Generated by Django 2.2.4 on 2020-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_profile_ordered_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('ordered', 'ordered'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('returned', 'returned')], max_length=10, null=True),
        ),
    ]
