# Generated by Django 2.2.4 on 2020-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20200511_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='delivered_products',
            field=models.ManyToManyField(blank=True, related_name='delivered_products', to='products.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='returned_products',
            field=models.ManyToManyField(blank=True, related_name='returned_products', to='products.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipped_products',
            field=models.ManyToManyField(blank=True, related_name='shipped_products', to='products.Product'),
        ),
    ]
