# Generated by Django 2.2.4 on 2020-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20200511_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivering_products',
            field=models.ManyToManyField(blank=True, related_name='delivering_products', to='products.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_confirmed_products',
            field=models.ManyToManyField(blank=True, related_name='order_confirmed', to='products.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_packing',
            field=models.ManyToManyField(blank=True, related_name='order_packing', to='products.Product'),
        ),
    ]
