# Generated by Django 2.2.4 on 2020-05-12 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
