# Generated by Django 2.2.4 on 2020-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20200512_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order_confirmed_products',
        ),
        migrations.AddField(
            model_name='admin',
            name='order_confirmed_products',
            field=models.ManyToManyField(blank=True, related_name='order_confirmed', to='products.Product'),
        ),
    ]
