# Generated by Django 2.2.4 on 2020-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20200512_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='delivered_products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delivering_products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='order_packing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ordered_products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='returned_products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipped_products',
        ),
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('confirmed', 'confirmed'), ('packing', 'packing'), ('shipped', 'shipped'), ('delivering', 'delivering'), ('delivered', 'delivered'), ('returned', 'returned')], default='ordered', max_length=20),
        ),
    ]
