# Generated by Django 2.2.4 on 2020-05-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20200512_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='order_confirmed_products',
        ),
    ]
