# Generated by Django 2.2.4 on 2020-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20200512_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Packing', 'Packing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Order Placed', max_length=20),
        ),
    ]
