# Generated by Django 2.2.4 on 2020-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20200520_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
