# Generated by Django 2.2.4 on 2020-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_profile_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Packing', 'Packing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Order Cancelled', 'Order Cancelled'), ('Return Request Placed', 'Return Request Placed'), ('Return Request Acknowledged', 'Return Request Acknowledged'), ('Courier Service Informed', 'Courier Service Informed'), ('Return Product Verified', 'Return Product Verified'), ('Refund Completed', 'Refund Completed')], default='Order Placed', max_length=200),
        ),
    ]
